<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_8oTucHWNEe2zo5QG_cHe4w" name="PremiumService" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_8oTucXWNEe2zo5QG_cHe4w" name="PremiumService">
      <elements xmi:type="process:Lane" xmi:id="_8oTucnWNEe2zo5QG_cHe4w" name="Employee lane" actor="_LEZkkHWOEe2zo5QG_cHe4w">
        <elements xmi:type="process:Task" xmi:id="_D-n_QHWPEe2zo5QG_cHe4w" name="Choose company" outgoing="_Pm8GMHWPEe2zo5QG_cHe4w" incoming="_IlzlwHWPEe2zo5QG_cHe4w" type="STANDARD" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D-n_QnWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D-n_QXWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D-n_Q3WPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D-n_RHWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D-n_RXWPEe2zo5QG_cHe4w" name="3" content="3" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D-n_RnWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D-n_SHWPEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D-n_R3WPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_D-n_SnWPEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_D-n_S3WPEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_D-n_SXWPEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_D-n_THWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_uxonoHWPEe2zo5QG_cHe4w" name="Review cv and letter" outgoing="_324U4HWPEe2zo5QG_cHe4w" incoming="_w0jhoHWPEe2zo5QG_cHe4w _52OWcHWPEe2zo5QG_cHe4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_uxononWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_uxonoXWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_uxono3WPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_uxonpHWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_uxonpXWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_uxonpnWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_uxonqHWPEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_uxonp3WPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_uxonqnWPEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_uxonq3WPEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_uxonqXWPEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_uxonrHWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_gMlNUHWQEe2zo5QG_cHe4w" name="Initiate interview" outgoing="_zR7GgHWQEe2zo5QG_cHe4w" incoming="_qZ4HwHWQEe2zo5QG_cHe4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gMl0YXWQEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gMl0YHWQEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gMl0YnWQEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_gMl0Y3WQEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_gMl0ZHWQEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_gMl0ZXWQEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_gMl0Z3WQEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_gMl0ZnWQEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_gMl0aXWQEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_gMl0anWQEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_gMl0aHWQEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_gMl0a3WQEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ySfNUHWREe2zo5QG_cHe4w" name="Give up" outgoing="_9ywLgHWREe2zo5QG_cHe4w _YYvysHWSEe2zo5QG_cHe4w" incoming="_0jiC4HWREe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ySfNUnWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ySfNUXWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ySfNU3WREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_C0Jo0HWSEe2zo5QG_cHe4w" name="Has more companies" outgoing="_78q-MHWSEe2zo5QG_cHe4w _V2VY8HWVEe2zo5QG_cHe4w" incoming="_FLJVYHWSEe2zo5QG_cHe4w _5QmHkHWUEe2zo5QG_cHe4w _YqzEoHWVEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_C0Jo0nWSEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_C0Jo0XWSEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_C0Jo03WSEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_GplCQHWSEe2zo5QG_cHe4w" name="End" incoming="_WkPAwHWVEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GplCQnWSEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GplCQXWSEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GplCQ3WSEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_RFN6sHWSEe2zo5QG_cHe4w" name="Organise interview" outgoing="_aVycQHWUEe2zo5QG_cHe4w" incoming="_YYvysHWSEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_RFOhwXWSEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_RFOhwHWSEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_RFOhwnWSEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_RFOhw3WSEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_RFOhxHWSEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RFOhxXWSEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_RFOhx3WSEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_RFOhxnWSEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ayKrsHWTEe2zo5QG_cHe4w" name="Grade candidate" outgoing="_u6IqEHWUEe2zo5QG_cHe4w" incoming="_bJZDcHWUEe2zo5QG_cHe4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ayKrsnWTEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ayKrsXWTEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ayKrs3WTEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ayKrtHWTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ayKrtXWTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ayKrtnWTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ayKruHWTEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ayKrt3WTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ayKrunWTEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_ayKru3WTEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ayKruXWTEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ayKrvHWTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_s0Q-MHWeEe2zo5QG_cHe4w" name="Send email" outgoing="_lX7tUHWPEe2zo5QG_cHe4w" incoming="_Pm8GMHWPEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OB-TgXWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OB-TgHWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OB-TgnWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OB-Tg3WPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OB-ThHWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OB-ThXWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OB-Th3WPEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_OB-ThnWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_vfoYQHWeEe2zo5QG_cHe4w" name="Send email" outgoing="_WkPAwHWVEe2zo5QG_cHe4w" incoming="_V2VY8HWVEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UJyXknWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UJyXkXWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UJyXk3WVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UJyXlHWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UJyXlXWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UJyXlnWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UJyXmHWVEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UJyXl3WVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_wRbBkHWeEe2zo5QG_cHe4w" name="Send emails" outgoing="_FLJVYHWSEe2zo5QG_cHe4w" incoming="_9ywLgHWREe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3aoL0nWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3aoL0XWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3aoL03WREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3aoL1HWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3aoL1XWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3aoL1nWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3aoL2HWREe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3aoL13WREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_HDgiAHWOEe2zo5QG_cHe4w" name="Boss lane" actor="_KPadUHWOEe2zo5QG_cHe4w">
        <elements xmi:type="process:Task" xmi:id="_8oTud3WNEe2zo5QG_cHe4w" name="Choose employee" outgoing="_IlzlwHWPEe2zo5QG_cHe4w" incoming="_8oTuiHWNEe2zo5QG_cHe4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8oTueHWNEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8oTueXWNEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8oTuenWNEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8oTue3WNEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8oTufHWNEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8oTufXWNEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8oTufnWNEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8oTuf3WNEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_8oTugHWNEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_8oTugXWNEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_8oTugnWNEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_8oTug3WNEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_poZc8HWPEe2zo5QG_cHe4w" name="Has cv and letter" outgoing="_w0jhoHWPEe2zo5QG_cHe4w _X1veMHWQEe2zo5QG_cHe4w" incoming="_lX7tUHWPEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_poaEAXWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_poaEAHWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_poaEAnWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_8Az-sHWPEe2zo5QG_cHe4w" name="Cv and letter good" outgoing="_8A3CAHWPEe2zo5QG_cHe4w _qZ4HwHWQEe2zo5QG_cHe4w" incoming="_324U4HWPEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8Az-snWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8Az-sXWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8Az-s3WPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_HF94wHWREe2zo5QG_cHe4w" name="Choose employee" outgoing="_bLmKQHWREe2zo5QG_cHe4w" incoming="_Kinl0HWREe2zo5QG_cHe4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HF94wnWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HF94wXWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HF94w3WREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HF94xHWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HF94xXWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HF94xnWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HF94yHWREe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HF94x3WREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HF94ynWREe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_HF94y3WREe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HF94yXWREe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HF94zHWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_-ic_kHWQEe2zo5QG_cHe4w" name="Parallel choosing" outgoing="_Fpi-EHWREe2zo5QG_cHe4w _Kinl0HWREe2zo5QG_cHe4w" incoming="_zR7GgHWQEe2zo5QG_cHe4w _78q-MHWSEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-idmoXWQEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-idmoHWQEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-idmonWQEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_XV7_8HWUEe2zo5QG_cHe4w" name="Grade parallel" outgoing="_bJZDcHWUEe2zo5QG_cHe4w _e72BYHWUEe2zo5QG_cHe4w _fw0hkHWUEe2zo5QG_cHe4w" incoming="_aVycQHWUEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XV7_8nWUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XV7_8XWUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XV7_83WUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_oEZr4HWVEe2zo5QG_cHe4w" name="End" incoming="_puQloHWVEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oEZr4nWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oEZr4XWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oEZr43WVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_zGfKMHWeEe2zo5QG_cHe4w" name="Send email" outgoing="_puQloHWVEe2zo5QG_cHe4w" incoming="_lhId4HWVEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_du-JInWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_du-JIXWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_du-JI3WVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_du-JJHWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_du-JJXWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_du-JJnWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_du-JKHWVEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_du-JJ3WVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ijFckHWOEe2zo5QG_cHe4w" name="Candidate lane" actor="_8oTui3WNEe2zo5QG_cHe4w">
        <elements xmi:type="process:StartEvent" xmi:id="_8oTuc3WNEe2zo5QG_cHe4w" name="Start" outgoing="_8oTuiHWNEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8oTudHWNEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8oTudXWNEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8oTudnWNEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_y0n78HWPEe2zo5QG_cHe4w" name="Change cv and letter" outgoing="_52OWcHWPEe2zo5QG_cHe4w" incoming="_8A3CAHWPEe2zo5QG_cHe4w _X1veMHWQEe2zo5QG_cHe4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_y0n78nWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_y0n78XWPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_y0n783WPEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_y0ojAHWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_y0ojAXWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_y0ojAnWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_y0ojBHWPEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_y0ojA3WPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_y0ojBnWPEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_y0ojB3WPEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_y0ojBXWPEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_y0ojCHWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_suZSoHWREe2zo5QG_cHe4w" name="Choose date" outgoing="_0jiC4HWREe2zo5QG_cHe4w" incoming="_wfrL4HWREe2zo5QG_cHe4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_suagwHWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_suZ5sHWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_suagwXWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_suagwnWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_suagw3WREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_suagxHWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_suagxnWREe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_suagxXWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_suagyHWREe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_suagyXWREe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_suagx3WREe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_suagynWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_O9q4AHWVEe2zo5QG_cHe4w" name="Rejected" outgoing="_YqzEoHWVEe2zo5QG_cHe4w _lhId4HWVEe2zo5QG_cHe4w" incoming="_XpyTkHWVEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_O9q4AnWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_O9q4AXWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_O9q4A3WVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_i2zp0HWOEe2zo5QG_cHe4w" name="HR Boss lane" actor="_RfVAoHWOEe2zo5QG_cHe4w">
        <elements xmi:type="process:Task" xmi:id="_uOS0kHWQEe2zo5QG_cHe4w" name="Choose company employees" outgoing="_aTZ-AHWREe2zo5QG_cHe4w" incoming="_Fpi-EHWREe2zo5QG_cHe4w" type="STANDARD" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_uOS0knWQEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_uOS0kXWQEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_uOS0k3WQEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_uOS0lHWQEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_uOS0lXWQEe2zo5QG_cHe4w" name="3" content="3" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_uOS0lnWQEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_uOS0mHWQEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_uOS0l3WQEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_uOS0mnWQEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_uOS0m3WQEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_uOS0mXWQEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_uOS0nHWQEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_T6D2UHWREe2zo5QG_cHe4w" name="Parallel merge" outgoing="_lnndMHWREe2zo5QG_cHe4w" incoming="_aTZ-AHWREe2zo5QG_cHe4w _bLmKQHWREe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_T6EdYXWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_T6EdYHWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_T6EdYnWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_HXr-EHWVEe2zo5QG_cHe4w" name="Final decision" outgoing="_XpyTkHWVEe2zo5QG_cHe4w" incoming="_MV3vUHWVEe2zo5QG_cHe4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HXr-EnWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HXr-EXWVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HXr-E3WVEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HXr-FHWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HXr-FXWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HXr-FnWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HXr-GHWVEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HXr-F3WVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HXslIHWVEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_HXslIXWVEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HXr-GXWVEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HXslInWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_jHr-cHWOEe2zo5QG_cHe4w" name="Project employee lane" actor="_U9fwoHWOEe2zo5QG_cHe4w">
        <elements xmi:type="process:ServiceTask" xmi:id="_dqUPcHWREe2zo5QG_cHe4w" name="Create dates" outgoing="_qSJSoHWREe2zo5QG_cHe4w" incoming="_lnndMHWREe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dqU2gXWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dqU2gHWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dqU2gnWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dqU2g3WREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dqU2hHWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dqU2hXWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dqU2h3WREe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dqU2hnWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_TFgiAHWTEe2zo5QG_cHe4w" name="Grade candidate" outgoing="_r9TskHWUEe2zo5QG_cHe4w" incoming="_fw0hkHWUEe2zo5QG_cHe4w" type="PARALLEL" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TFhJEXWTEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TFhJEHWTEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TFhJEnWTEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TFhJE3WTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TFhJFHWTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TFhJFXWTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TFhJF3WTEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TFhJFnWTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_TFhJGXWTEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_TFhJGnWTEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_TFhJGHWTEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_TFhJG3WTEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_npCbAHWUEe2zo5QG_cHe4w" name="Grade Parallel merge" outgoing="_0qv90HWUEe2zo5QG_cHe4w" incoming="_qgvA4HWUEe2zo5QG_cHe4w _r9TskHWUEe2zo5QG_cHe4w _u6IqEHWUEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_npCbAnWUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_npCbAXWUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_npCbA3WUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_w2PxcHWUEe2zo5QG_cHe4w" name="Accepted" outgoing="_5QmHkHWUEe2zo5QG_cHe4w _MV3vUHWVEe2zo5QG_cHe4w" incoming="_0qv90HWUEe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_w2PxcnWUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_w2PxcXWUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_w2Pxc3WUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_yEPqEHWeEe2zo5QG_cHe4w" name="Send email" outgoing="_wfrL4HWREe2zo5QG_cHe4w" incoming="_qSJSoHWREe2zo5QG_cHe4w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oSg9MXWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oSg9MHWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oSg9MnWREe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oSg9M3WREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oSg9NHWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oSg9NXWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oSg9N3WREe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oSg9NnWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_TtK7wHWPEe2zo5QG_cHe4w" name="HR employee lane" actor="_WXa7gHWPEe2zo5QG_cHe4w">
        <elements xmi:type="process:Task" xmi:id="_Tk27AHWUEe2zo5QG_cHe4w" name="Grade candidate" outgoing="_qgvA4HWUEe2zo5QG_cHe4w" incoming="_e72BYHWUEe2zo5QG_cHe4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Tk3iEXWUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Tk3iEHWUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Tk3iEnWUEe2zo5QG_cHe4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Tk3iE3WUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Tk3iFHWUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Tk3iFXWUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Tk3iF3WUEe2zo5QG_cHe4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Tk3iFnWUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Tk3iGXWUEe2zo5QG_cHe4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Tk3iGnWUEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Tk3iGHWUEe2zo5QG_cHe4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Tk3iG3WUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_8oTuhHWNEe2zo5QG_cHe4w">
        <targetForm xmi:type="expression:Expression" xmi:id="_8oTuhXWNEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_8oTuhnWNEe2zo5QG_cHe4w">
        <targetForm xmi:type="expression:Expression" xmi:id="_8oTuh3WNEe2zo5QG_cHe4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8oTuiHWNEe2zo5QG_cHe4w" target="_8oTud3WNEe2zo5QG_cHe4w" source="_8oTuc3WNEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8oTuiXWNEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_8oTuinWNEe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IlzlwHWPEe2zo5QG_cHe4w" target="_D-n_QHWPEe2zo5QG_cHe4w" source="_8oTud3WNEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Il0M0HWPEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_Il0M0XWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Pm8GMHWPEe2zo5QG_cHe4w" target="_s0Q-MHWeEe2zo5QG_cHe4w" source="_D-n_QHWPEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Pm8GMXWPEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_Pm8GMnWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lX7tUHWPEe2zo5QG_cHe4w" target="_poZc8HWPEe2zo5QG_cHe4w" source="_s0Q-MHWeEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lX7tUXWPEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_lX7tUnWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_w0jhoHWPEe2zo5QG_cHe4w" target="_uxonoHWPEe2zo5QG_cHe4w" source="_poZc8HWPEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_w0kIsHWPEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_w0kIsXWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_324U4HWPEe2zo5QG_cHe4w" target="_8Az-sHWPEe2zo5QG_cHe4w" source="_uxonoHWPEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_32478HWPEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_32478XWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_52OWcHWPEe2zo5QG_cHe4w" target="_uxonoHWPEe2zo5QG_cHe4w" source="_y0n78HWPEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_52OWcXWPEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_52OWcnWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8A3CAHWPEe2zo5QG_cHe4w" target="_y0n78HWPEe2zo5QG_cHe4w" source="_8Az-sHWPEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8A3CAXWPEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_8A3CAnWPEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_X1veMHWQEe2zo5QG_cHe4w" target="_y0n78HWPEe2zo5QG_cHe4w" source="_poZc8HWPEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_X1veMXWQEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_X1veMnWQEe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qZ4HwHWQEe2zo5QG_cHe4w" target="_gMlNUHWQEe2zo5QG_cHe4w" source="_8Az-sHWPEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qZ4HwXWQEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_qZ4HwnWQEe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zR7GgHWQEe2zo5QG_cHe4w" target="_-ic_kHWQEe2zo5QG_cHe4w" source="_gMlNUHWQEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zR7GgXWQEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_zR7GgnWQEe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Fpi-EHWREe2zo5QG_cHe4w" target="_uOS0kHWQEe2zo5QG_cHe4w" source="_-ic_kHWQEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FpjlIHWREe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_FpjlIXWREe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Kinl0HWREe2zo5QG_cHe4w" target="_HF94wHWREe2zo5QG_cHe4w" source="_-ic_kHWQEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KioM4HWREe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_KioM4XWREe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aTZ-AHWREe2zo5QG_cHe4w" target="_T6D2UHWREe2zo5QG_cHe4w" source="_uOS0kHWQEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aTZ-AXWREe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_aTZ-AnWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bLmKQHWREe2zo5QG_cHe4w" target="_T6D2UHWREe2zo5QG_cHe4w" source="_HF94wHWREe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bLmxUHWREe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_bLmxUXWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lnndMHWREe2zo5QG_cHe4w" target="_dqUPcHWREe2zo5QG_cHe4w" source="_T6D2UHWREe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lnndMXWREe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_lnndMnWREe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qSJSoHWREe2zo5QG_cHe4w" target="_yEPqEHWeEe2zo5QG_cHe4w" source="_dqUPcHWREe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qSJSoXWREe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_qSJSonWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wfrL4HWREe2zo5QG_cHe4w" target="_suZSoHWREe2zo5QG_cHe4w" source="_yEPqEHWeEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wfrL4XWREe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_wfrL4nWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0jiC4HWREe2zo5QG_cHe4w" target="_ySfNUHWREe2zo5QG_cHe4w" source="_suZSoHWREe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0jiC4XWREe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_0jiC4nWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9ywLgHWREe2zo5QG_cHe4w" target="_wRbBkHWeEe2zo5QG_cHe4w" source="_ySfNUHWREe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9ywLgXWREe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_9ywykHWREe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FLJVYHWSEe2zo5QG_cHe4w" target="_C0Jo0HWSEe2zo5QG_cHe4w" source="_wRbBkHWeEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FLJ8cHWSEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_FLJ8cXWSEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YYvysHWSEe2zo5QG_cHe4w" target="_RFN6sHWSEe2zo5QG_cHe4w" source="_ySfNUHWREe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YYvysXWSEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_YYvysnWSEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_78q-MHWSEe2zo5QG_cHe4w" target="_-ic_kHWQEe2zo5QG_cHe4w" source="_C0Jo0HWSEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_78q-MXWSEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_78q-MnWSEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aVycQHWUEe2zo5QG_cHe4w" target="_XV7_8HWUEe2zo5QG_cHe4w" source="_RFN6sHWSEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aVycQXWUEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_aVycQnWUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bJZDcHWUEe2zo5QG_cHe4w" target="_ayKrsHWTEe2zo5QG_cHe4w" source="_XV7_8HWUEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bJZDcXWUEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_bJZDcnWUEe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_e72BYHWUEe2zo5QG_cHe4w" target="_Tk27AHWUEe2zo5QG_cHe4w" source="_XV7_8HWUEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_e72BYXWUEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_e72BYnWUEe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fw0hkHWUEe2zo5QG_cHe4w" target="_TFgiAHWTEe2zo5QG_cHe4w" source="_XV7_8HWUEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fw0hkXWUEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_fw0hknWUEe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qgvA4HWUEe2zo5QG_cHe4w" target="_npCbAHWUEe2zo5QG_cHe4w" source="_Tk27AHWUEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qgvA4XWUEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_qgvA4nWUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r9TskHWUEe2zo5QG_cHe4w" target="_npCbAHWUEe2zo5QG_cHe4w" source="_TFgiAHWTEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r9TskXWUEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_r9TsknWUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_u6IqEHWUEe2zo5QG_cHe4w" target="_npCbAHWUEe2zo5QG_cHe4w" source="_ayKrsHWTEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_u6JRIHWUEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_u6JRIXWUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0qv90HWUEe2zo5QG_cHe4w" target="_w2PxcHWUEe2zo5QG_cHe4w" source="_npCbAHWUEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0qv90XWUEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_0qv90nWUEe2zo5QG_cHe4w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5QmHkHWUEe2zo5QG_cHe4w" target="_C0Jo0HWSEe2zo5QG_cHe4w" source="_w2PxcHWUEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5QmuoHWUEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_5QmuoXWUEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MV3vUHWVEe2zo5QG_cHe4w" target="_HXr-EHWVEe2zo5QG_cHe4w" source="_w2PxcHWUEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MV3vUXWVEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_MV3vUnWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_V2VY8HWVEe2zo5QG_cHe4w" target="_vfoYQHWeEe2zo5QG_cHe4w" source="_C0Jo0HWSEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_V2VY8XWVEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_V2VY8nWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WkPAwHWVEe2zo5QG_cHe4w" target="_GplCQHWSEe2zo5QG_cHe4w" source="_vfoYQHWeEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WkPAwXWVEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_WkPAwnWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XpyTkHWVEe2zo5QG_cHe4w" target="_O9q4AHWVEe2zo5QG_cHe4w" source="_HXr-EHWVEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XpyTkXWVEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_XpyTknWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YqzEoHWVEe2zo5QG_cHe4w" target="_C0Jo0HWSEe2zo5QG_cHe4w" source="_O9q4AHWVEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YqzEoXWVEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_YqzEonWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lhId4HWVEe2zo5QG_cHe4w" target="_zGfKMHWeEe2zo5QG_cHe4w" source="_O9q4AHWVEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lhId4XWVEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_lhId4nWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_puQloHWVEe2zo5QG_cHe4w" target="_oEZr4HWVEe2zo5QG_cHe4w" source="_zGfKMHWeEe2zo5QG_cHe4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_puQloXWVEe2zo5QG_cHe4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_puQlonWVEe2zo5QG_cHe4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_8oTui3WNEe2zo5QG_cHe4w" name="Candidate" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_KPadUHWOEe2zo5QG_cHe4w" name="Boss"/>
      <actors xmi:type="process:Actor" xmi:id="_LEZkkHWOEe2zo5QG_cHe4w" name="Employee"/>
      <actors xmi:type="process:Actor" xmi:id="_RfVAoHWOEe2zo5QG_cHe4w" name="HR Boss"/>
      <actors xmi:type="process:Actor" xmi:id="_U9fwoHWOEe2zo5QG_cHe4w" name="Project employee"/>
      <actors xmi:type="process:Actor" xmi:id="_WXa7gHWPEe2zo5QG_cHe4w" name="HR employee"/>
      <contract xmi:type="process:Contract" xmi:id="_8oTujHWNEe2zo5QG_cHe4w"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8oTujXWNEe2zo5QG_cHe4w">
        <name xmi:type="expression:Expression" xmi:id="_8oTujnWNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8oTuj3WNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8oTukHWNEe2zo5QG_cHe4w">
        <name xmi:type="expression:Expression" xmi:id="_8oTukXWNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8oTuknWNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8oTuk3WNEe2zo5QG_cHe4w">
        <name xmi:type="expression:Expression" xmi:id="_8oTulHWNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8oTulXWNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8oTulnWNEe2zo5QG_cHe4w">
        <name xmi:type="expression:Expression" xmi:id="_8oTul3WNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8oTumHWNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8oTumXWNEe2zo5QG_cHe4w">
        <name xmi:type="expression:Expression" xmi:id="_8oTumnWNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8oTum3WNEe2zo5QG_cHe4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_8oTunHWNEe2zo5QG_cHe4w" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_8oTunXWNEe2zo5QG_cHe4w" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_8oTunnWNEe2zo5QG_cHe4w" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_8oTun3WNEe2zo5QG_cHe4w" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_8oTuoHWNEe2zo5QG_cHe4w" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_8oTuoXWNEe2zo5QG_cHe4w" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_8oTuonWNEe2zo5QG_cHe4w" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_8oTuo3WNEe2zo5QG_cHe4w" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_8oTupHWNEe2zo5QG_cHe4w" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_8oTupXWNEe2zo5QG_cHe4w" type="Process" element="_8oTucHWNEe2zo5QG_cHe4w" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_8oTupnWNEe2zo5QG_cHe4w" type="2007" element="_8oTucXWNEe2zo5QG_cHe4w">
      <children xmi:type="notation:DecorationNode" xmi:id="_8oTup3WNEe2zo5QG_cHe4w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_8oTuqHWNEe2zo5QG_cHe4w" type="7001">
        <children xmi:type="notation:Node" xmi:id="_8oTuqXWNEe2zo5QG_cHe4w" type="3007" element="_8oTucnWNEe2zo5QG_cHe4w">
          <children xmi:type="notation:DecorationNode" xmi:id="_8oTuqnWNEe2zo5QG_cHe4w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_8oTuq3WNEe2zo5QG_cHe4w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_D-omUHWPEe2zo5QG_cHe4w" type="3005" element="_D-n_QHWPEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_D-omUnWPEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D-omUXWPEe2zo5QG_cHe4w" x="52" y="42" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uxpOsHWPEe2zo5QG_cHe4w" type="3005" element="_uxonoHWPEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uxpOsnWPEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uxpOsXWPEe2zo5QG_cHe4w" x="470" y="54" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gMmbcHWQEe2zo5QG_cHe4w" type="3005" element="_gMlNUHWQEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_gMmbcnWQEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gMmbcXWQEe2zo5QG_cHe4w" x="752" y="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ySf0YHWREe2zo5QG_cHe4w" type="3008" element="_ySfNUHWREe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ySf0YnWREe2zo5QG_cHe4w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ySf0Y3WREe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ySf0YXWREe2zo5QG_cHe4w" x="1028" y="131"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_C0KP4HWSEe2zo5QG_cHe4w" type="3008" element="_C0Jo0HWSEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_C0KP4nWSEe2zo5QG_cHe4w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_C0KP43WSEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_C0KP4XWSEe2zo5QG_cHe4w" x="902" y="13"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GplpUHWSEe2zo5QG_cHe4w" type="3003" element="_GplCQHWSEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_GplpUnWSEe2zo5QG_cHe4w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GplpU3WSEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GplpUXWSEe2zo5QG_cHe4w" x="909" y="216"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RFOhyHWSEe2zo5QG_cHe4w" type="3027" element="_RFN6sHWSEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_RFPI0HWSEe2zo5QG_cHe4w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RFOhyXWSEe2zo5QG_cHe4w" x="1118" y="192"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ayKrvXWTEe2zo5QG_cHe4w" type="3005" element="_ayKrsHWTEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ayLSwHWTEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ayKrvnWTEe2zo5QG_cHe4w" x="1358" y="205"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s0RlSHWeEe2zo5QG_cHe4w" type="3027" element="_s0Q-MHWeEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s0RlSnWeEe2zo5QG_cHe4w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s0RlSXWeEe2zo5QG_cHe4w" x="278" y="55" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vfo_WHWeEe2zo5QG_cHe4w" type="3027" element="_vfoYQHWeEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vfo_WnWeEe2zo5QG_cHe4w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vfo_WXWeEe2zo5QG_cHe4w" x="896" y="117" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wRboqHWeEe2zo5QG_cHe4w" type="3027" element="_wRbBkHWeEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wRboqnWeEe2zo5QG_cHe4w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wRboqXWeEe2zo5QG_cHe4w" x="1131" y="10" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_8oTus3WNEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_8oTutHWNEe2zo5QG_cHe4w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_8oTutXWNEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_8oTutnWNEe2zo5QG_cHe4w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8oTut3WNEe2zo5QG_cHe4w" x="53" y="10" width="1490" height="305"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_HDhwIHWOEe2zo5QG_cHe4w" type="3007" element="_HDgiAHWOEe2zo5QG_cHe4w">
          <children xmi:type="notation:DecorationNode" xmi:id="_HDhwJXWOEe2zo5QG_cHe4w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_HDhwJnWOEe2zo5QG_cHe4w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_8oTurHWNEe2zo5QG_cHe4w" type="3005" element="_8oTud3WNEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8oTurXWNEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8oTurnWNEe2zo5QG_cHe4w" x="53" y="25" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_poaEA3WPEe2zo5QG_cHe4w" type="3008" element="_poZc8HWPEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_poaEBXWPEe2zo5QG_cHe4w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_poarEHWPEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_poaEBHWPEe2zo5QG_cHe4w" x="300" y="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8Az-tHWPEe2zo5QG_cHe4w" type="3008" element="_8Az-sHWPEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8Az-tnWPEe2zo5QG_cHe4w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8Az-t3WPEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8Az-tXWPEe2zo5QG_cHe4w" x="650" y="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HF94zXWREe2zo5QG_cHe4w" type="3005" element="_HF94wHWREe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HF-f0XWREe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HF-f0HWREe2zo5QG_cHe4w" x="876" y="82" width="134" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-ieNsHWQEe2zo5QG_cHe4w" type="3009" element="_-ic_kHWQEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_-ie0wHWQEe2zo5QG_cHe4w" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_-ie0wXWQEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-ieNsXWQEe2zo5QG_cHe4w" x="806" y="107"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XV7_9HWUEe2zo5QG_cHe4w" type="3009" element="_XV7_8HWUEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XV8nAHWUEe2zo5QG_cHe4w" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XV8nAXWUEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XV7_9XWUEe2zo5QG_cHe4w" x="1146" y="23"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oEaS8HWVEe2zo5QG_cHe4w" type="3003" element="_oEZr4HWVEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_oEaS8nWVEe2zo5QG_cHe4w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oEaS83WVEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oEaS8XWVEe2zo5QG_cHe4w" x="1657" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zGfKOXWeEe2zo5QG_cHe4w" type="3027" element="_zGfKMHWeEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zGfKO3WeEe2zo5QG_cHe4w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zGfKOnWeEe2zo5QG_cHe4w" x="1622" y="151" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_HDhwIXWOEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_HDhwInWOEe2zo5QG_cHe4w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_HDhwI3WOEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_HDhwJ3WOEe2zo5QG_cHe4w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HDhwJHWOEe2zo5QG_cHe4w" x="53" y="175" width="1142" height="214"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_ijGDoHWOEe2zo5QG_cHe4w" type="3007" element="_ijFckHWOEe2zo5QG_cHe4w">
          <children xmi:type="notation:DecorationNode" xmi:id="_ijGDpXWOEe2zo5QG_cHe4w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ijGDpnWOEe2zo5QG_cHe4w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_8oTur3WNEe2zo5QG_cHe4w" type="3002" element="_8oTuc3WNEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8oTusHWNEe2zo5QG_cHe4w" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8oTusXWNEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8oTusnWNEe2zo5QG_cHe4w" x="86" y="55"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_y0ojCXWPEe2zo5QG_cHe4w" type="3005" element="_y0n78HWPEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_y0ojC3WPEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_y0ojCnWPEe2zo5QG_cHe4w" x="566" y="54" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_suagy3WREe2zo5QG_cHe4w" type="3005" element="_suZSoHWREe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_subH0HWREe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_suagzHWREe2zo5QG_cHe4w" x="1017" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_O9rfEHWVEe2zo5QG_cHe4w" type="3008" element="_O9q4AHWVEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_O9rfEnWVEe2zo5QG_cHe4w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_O9rfE3WVEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_O9rfEXWVEe2zo5QG_cHe4w" x="1598" y="87"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ijGDoXWOEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ijGDonWOEe2zo5QG_cHe4w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ijGDo3WOEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ijGDp3WOEe2zo5QG_cHe4w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ijGDpHWOEe2zo5QG_cHe4w" x="53" y="336" width="1142" height="182"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_i2zp0XWOEe2zo5QG_cHe4w" type="3007" element="_i2zp0HWOEe2zo5QG_cHe4w">
          <children xmi:type="notation:DecorationNode" xmi:id="_i20Q4XWOEe2zo5QG_cHe4w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_i20Q4nWOEe2zo5QG_cHe4w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_uOS0nXWQEe2zo5QG_cHe4w" type="3005" element="_uOS0kHWQEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uOTboHWQEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uOS0nnWQEe2zo5QG_cHe4w" x="752" y="47" width="163" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_T6EdY3WREe2zo5QG_cHe4w" type="3009" element="_T6D2UHWREe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_T6EdZXWREe2zo5QG_cHe4w" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_T6EdZnWREe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_T6EdZHWREe2zo5QG_cHe4w" x="974" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HXslI3WVEe2zo5QG_cHe4w" type="3005" element="_HXr-EHWVEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HXtMMHWVEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HXslJHWVEe2zo5QG_cHe4w" x="1574" y="74"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_i2zp0nWOEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_i2zp03WOEe2zo5QG_cHe4w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_i2zp1HWOEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_i20Q43WOEe2zo5QG_cHe4w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_i20Q4HWOEe2zo5QG_cHe4w" x="53" y="571" width="1142" height="199"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_jHslgHWOEe2zo5QG_cHe4w" type="3007" element="_jHr-cHWOEe2zo5QG_cHe4w">
          <children xmi:type="notation:DecorationNode" xmi:id="_jHslhXWOEe2zo5QG_cHe4w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jHslhnWOEe2zo5QG_cHe4w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_dqU2iHWREe2zo5QG_cHe4w" type="3027" element="_dqUPcHWREe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dqVdkHWREe2zo5QG_cHe4w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dqU2iXWREe2zo5QG_cHe4w" x="752" y="40" width="121" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TFhwIHWTEe2zo5QG_cHe4w" type="3005" element="_TFgiAHWTEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TFhwInWTEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TFhwIXWTEe2zo5QG_cHe4w" x="1238" y="40" width="121" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_npDCEHWUEe2zo5QG_cHe4w" type="3009" element="_npCbAHWUEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_npDCEnWUEe2zo5QG_cHe4w" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_npDCE3WUEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_npDCEXWUEe2zo5QG_cHe4w" x="1402" y="48"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w2QYgHWUEe2zo5QG_cHe4w" type="3008" element="_w2PxcHWUEe2zo5QG_cHe4w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_w2QYgnWUEe2zo5QG_cHe4w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_w2QYg3WUEe2zo5QG_cHe4w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w2QYgXWUEe2zo5QG_cHe4w" x="1526" y="48"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yEPqGXWeEe2zo5QG_cHe4w" type="3027" element="_yEPqEHWeEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yEPqG3WeEe2zo5QG_cHe4w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yEPqGnWeEe2zo5QG_cHe4w" x="1017" y="45" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jHslgXWOEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jHslgnWOEe2zo5QG_cHe4w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jHslg3WOEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jHslh3WOEe2zo5QG_cHe4w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jHslhHWOEe2zo5QG_cHe4w" x="53" y="439" width="1292" height="156"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_TtLi0HWPEe2zo5QG_cHe4w" type="3007" element="_TtK7wHWPEe2zo5QG_cHe4w">
          <children xmi:type="notation:DecorationNode" xmi:id="_TtLi1XWPEe2zo5QG_cHe4w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_TtLi1nWPEe2zo5QG_cHe4w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Tk3iHHWUEe2zo5QG_cHe4w" type="3005" element="_Tk27AHWUEe2zo5QG_cHe4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Tk3iHnWUEe2zo5QG_cHe4w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Tk3iHXWUEe2zo5QG_cHe4w" x="1166" y="60" width="134" height="67"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_TtLi0XWPEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_TtLi0nWPEe2zo5QG_cHe4w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_TtLi03WPEe2zo5QG_cHe4w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_TtLi13WPEe2zo5QG_cHe4w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TtLi1HWPEe2zo5QG_cHe4w" x="53" y="1056" width="1490" height="200"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_8oTuuHWNEe2zo5QG_cHe4w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_8oTuuXWNEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_8oTuunWNEe2zo5QG_cHe4w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_8oTuu3WNEe2zo5QG_cHe4w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8oTuvHWNEe2zo5QG_cHe4w" width="1837" height="412"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_8oTuvXWNEe2zo5QG_cHe4w"/>
    <edges xmi:type="notation:Connector" xmi:id="_8oTuvnWNEe2zo5QG_cHe4w" type="4001" element="_8oTuiHWNEe2zo5QG_cHe4w" source="_8oTur3WNEe2zo5QG_cHe4w" target="_8oTurHWNEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8oTuv3WNEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8oTuwHWNEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8oTuwXWNEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8oTuwnWNEe2zo5QG_cHe4w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Il0M0nWPEe2zo5QG_cHe4w" type="4001" element="_IlzlwHWPEe2zo5QG_cHe4w" source="_8oTurHWNEe2zo5QG_cHe4w" target="_D-omUHWPEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Il0M1XWPEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Il0M1nWPEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Il0M03WPEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Il0M1HWPEe2zo5QG_cHe4w" points="[1, -11, 1, 73]$[1, -74, 1, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Il1a8HWPEe2zo5QG_cHe4w" id="(0.4365079365079365,0.23809523809523808)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Il1a8XWPEe2zo5QG_cHe4w" id="(0.3783783783783784,0.8243243243243243)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pm8GM3WPEe2zo5QG_cHe4w" type="4001" element="_Pm8GMHWPEe2zo5QG_cHe4w" source="_D-omUHWPEe2zo5QG_cHe4w" target="_s0RlSHWeEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pm8GNnWPEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pm8GN3WPEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pm8GNHWPEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pm8GNXWPEe2zo5QG_cHe4w" points="[55, 2, -66, 1]$[122, 20, 1, 19]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Pm97YHWPEe2zo5QG_cHe4w" id="(0.1,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lX8UYHWPEe2zo5QG_cHe4w" type="4001" element="_lX7tUHWPEe2zo5QG_cHe4w" source="_s0RlSHWeEe2zo5QG_cHe4w" target="_poaEA3WPEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lX8UY3WPEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lX8UZHWPEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lX8UYXWPEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lX8UYnWPEe2zo5QG_cHe4w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_w0qPUHWPEe2zo5QG_cHe4w" type="4001" element="_w0jhoHWPEe2zo5QG_cHe4w" source="_poaEA3WPEe2zo5QG_cHe4w" target="_uxpOsHWPEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_w0q2YHWPEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_w0q2YXWPEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_w0qPUXWPEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_w0qPUnWPEe2zo5QG_cHe4w" points="[9, -7, -160, 126]$[170, -122, 1, 11]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_w0sEgHWPEe2zo5QG_cHe4w" id="(0.6111111111111112,0.7777777777777778)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_32478nWPEe2zo5QG_cHe4w" type="4001" element="_324U4HWPEe2zo5QG_cHe4w" source="_uxpOsHWPEe2zo5QG_cHe4w" target="_8Az-tHWPEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_32479XWPEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_32479nWPEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_324783WPEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_32479HWPEe2zo5QG_cHe4w" points="[14, 0, -87, -195]$[104, 0, 3, -195]$[104, 176, 3, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_326KEHWPEe2zo5QG_cHe4w" id="(0.8888888888888888,0.47619047619047616)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_52OWc3WPEe2zo5QG_cHe4w" type="4001" element="_52OWcHWPEe2zo5QG_cHe4w" source="_y0ojCXWPEe2zo5QG_cHe4w" target="_uxpOsHWPEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_52OWdnWPEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_52OWd3WPEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_52OWdHWPEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_52OWdXWPEe2zo5QG_cHe4w" points="[-4, -31, 37, 307]$[-4, -336, 37, 2]$[-33, -336, 8, 2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8A3pEHWPEe2zo5QG_cHe4w" type="4001" element="_8A3CAHWPEe2zo5QG_cHe4w" source="_8Az-tHWPEe2zo5QG_cHe4w" target="_y0ojCXWPEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8A3pE3WPEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8A3pFHWPEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8A3pEXWPEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8A3pEnWPEe2zo5QG_cHe4w" points="[-10, -6, 97, -151]$[-10, 78, 97, -67]$[-5, 78, 102, -67]$[-5, 143, 102, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_m6l9cHWQEe2zo5QG_cHe4w" id="(0.5813953488372093,0.9767441860465116)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AqPn8HWQEe2zo5QG_cHe4w" id="(0.8650793650793651,0.015873015873015872)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_X12L4HWQEe2zo5QG_cHe4w" type="4001" element="_X1veMHWQEe2zo5QG_cHe4w" source="_poaEA3WPEe2zo5QG_cHe4w" target="_y0ojCXWPEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_X12L43WQEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_X12L5HWQEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_X12L4XWQEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_X12L4nWQEe2zo5QG_cHe4w" points="[0, 22, -250, -121]$[0, 140, -250, -3]$[245, 140, -5, -3]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_X14BEHWQEe2zo5QG_cHe4w" id="(0.03968253968253968,0.5079365079365079)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qZ9nUHWQEe2zo5QG_cHe4w" type="4001" element="_qZ4HwHWQEe2zo5QG_cHe4w" source="_8Az-tHWPEe2zo5QG_cHe4w" target="_gMmbcHWQEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qZ9nU3WQEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qZ9nVHWQEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qZ9nUXWQEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qZ9nUnWQEe2zo5QG_cHe4w" points="[22, 0, -109, 193]$[87, 0, -44, 193]$[87, -168, -44, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zR7Gg3WQEe2zo5QG_cHe4w" type="4001" element="_zR7GgHWQEe2zo5QG_cHe4w" source="_gMmbcHWQEe2zo5QG_cHe4w" target="_-ieNsHWQEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zR7tkHWQEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zR7tkXWQEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zR7GhHWQEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zR7GhXWQEe2zo5QG_cHe4w" points="[1, 18, 1, -399]$[1, 399, 1, -18]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FpjlInWREe2zo5QG_cHe4w" type="4001" element="_Fpi-EHWREe2zo5QG_cHe4w" source="_-ieNsHWQEe2zo5QG_cHe4w" target="_uOS0nXWQEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FpjlJXWREe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FpjlJnWREe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FpjlI3WREe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FpjlJHWREe2zo5QG_cHe4w" points="[-5, 12, 1, -146]$[-5, 149, 1, -9]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FpkzQHWREe2zo5QG_cHe4w" id="(0.4171779141104294,0.16049382716049382)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KioM4nWREe2zo5QG_cHe4w" type="4001" element="_Kinl0HWREe2zo5QG_cHe4w" source="_-ieNsHWQEe2zo5QG_cHe4w" target="_HF94zXWREe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KioM5XWREe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KioM5nWREe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KioM43WREe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KioM5HWREe2zo5QG_cHe4w" points="[7, -9, -79, 88]$[84, -122, -2, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aTalEHWREe2zo5QG_cHe4w" type="4001" element="_aTZ-AHWREe2zo5QG_cHe4w" source="_uOS0nXWQEe2zo5QG_cHe4w" target="_T6EdY3WREe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aTalE3WREe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aTalFHWREe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aTalEXWREe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aTalEnWREe2zo5QG_cHe4w" points="[11, 2, -61, -1]$[65, -6, -7, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aTbzMHWREe2zo5QG_cHe4w" id="(0.9079754601226994,0.4567901234567901)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bLmxUnWREe2zo5QG_cHe4w" type="4001" element="_bLmKQHWREe2zo5QG_cHe4w" source="_HF94zXWREe2zo5QG_cHe4w" target="_T6EdY3WREe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bLnYYHWREe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bLnYYXWREe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bLmxU3WREe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bLmxVHWREe2zo5QG_cHe4w" points="[4, 25, -36, -251]$[42, 262, 2, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cmNHEHWREe2zo5QG_cHe4w" id="(0.8656716417910447,0.9402985074626866)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lnoEQHWREe2zo5QG_cHe4w" type="4001" element="_lnndMHWREe2zo5QG_cHe4w" source="_T6EdY3WREe2zo5QG_cHe4w" target="_dqU2iHWREe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lnoEQ3WREe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lnoERHWREe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lnoEQXWREe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lnoEQnWREe2zo5QG_cHe4w" points="[0, 22, 187, -144]$[0, 176, 187, 10]$[-122, 176, 65, 10]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lnpSYHWREe2zo5QG_cHe4w" id="(0.4628099173553719,0.23333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qSJ5sHWREe2zo5QG_cHe4w" type="4001" element="_qSJSoHWREe2zo5QG_cHe4w" source="_dqU2iHWREe2zo5QG_cHe4w" target="_yEPqGXWeEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qSJ5s3WREe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qSJ5tHWREe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qSJ5sXWREe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qSJ5snWREe2zo5QG_cHe4w" points="[46, 7, -167, 1]$[214, 19, 1, 13]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qSKgwHWREe2zo5QG_cHe4w" id="(0.79,0.66)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wfry8HWREe2zo5QG_cHe4w" type="4001" element="_wfrL4HWREe2zo5QG_cHe4w" source="_yEPqGXWeEe2zo5QG_cHe4w" target="_suagy3WREe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wfry83WREe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wfry9HWREe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wfry8XWREe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wfry8nWREe2zo5QG_cHe4w" points="[1, -2, 1, 184]$[1, -192, 1, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wftBEHWREe2zo5QG_cHe4w" id="(0.37,0.14)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0jiC43WREe2zo5QG_cHe4w" type="4001" element="_0jiC4HWREe2zo5QG_cHe4w" source="_suagy3WREe2zo5QG_cHe4w" target="_ySf0YHWREe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0jiC5nWREe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0jiC53WREe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0jiC5HWREe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0jiC5XWREe2zo5QG_cHe4w" points="[49, 25, -81, -36]$[49, 64, -81, 3]$[111, 64, -19, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9ywykXWREe2zo5QG_cHe4w" type="4001" element="_9ywLgHWREe2zo5QG_cHe4w" source="_ySf0YHWREe2zo5QG_cHe4w" target="_wRboqHWeEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9ywylHWREe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9ywylXWREe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9ywyknWREe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9ywyk3WREe2zo5QG_cHe4w" points="[11, -10, -121, 107]$[117, -10, -15, 107]$[117, -48, -15, 69]$[105, -48, -27, 69]$[105, -92, -27, 25]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0inAYHWSEe2zo5QG_cHe4w" id="(0.91,0.92)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FLJ8cnWSEe2zo5QG_cHe4w" type="4001" element="_FLJVYHWSEe2zo5QG_cHe4w" source="_wRboqHWeEe2zo5QG_cHe4w" target="_C0KP4HWSEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FLJ8dXWSEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FLJ8dnWSEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FLJ8c3WSEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FLJ8dHWSEe2zo5QG_cHe4w" points="[-14, -5, 208, -7]$[-220, -18, 2, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FLLKkHWSEe2zo5QG_cHe4w" id="(0.14,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YY15UHWSEe2zo5QG_cHe4w" type="4001" element="_YYvysHWSEe2zo5QG_cHe4w" source="_ySf0YHWREe2zo5QG_cHe4w" target="_RFOhyHWSEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YY15U3WSEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YY15VHWSEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YY15UXWSEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YY15UnWSEe2zo5QG_cHe4w" points="[-9, 1, 0, -95]$[-21, 94, -12, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Y0cQMHWSEe2zo5QG_cHe4w" id="(0.5581395348837209,0.9767441860465116)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_78v2sHWSEe2zo5QG_cHe4w" type="4001" element="_78q-MHWSEe2zo5QG_cHe4w" source="_C0KP4HWSEe2zo5QG_cHe4w" target="_-ieNsHWQEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_78wdwHWSEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_78wdwXWSEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_78v2sXWSEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_78v2snWSEe2zo5QG_cHe4w" points="[-21, 0, 75, -367]$[-45, 0, 51, -367]$[-45, 182, 51, -185]$[-92, 182, 4, -185]$[-92, 349, 4, -18]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aVycQ3WUEe2zo5QG_cHe4w" type="4001" element="_aVycQHWUEe2zo5QG_cHe4w" source="_RFOhyHWSEe2zo5QG_cHe4w" target="_XV7_9HWUEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aVycRnWUEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aVycR3WUEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aVycRHWUEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aVycRXWUEe2zo5QG_cHe4w" points="[-2, 19, 1, -69]$[-2, 85, 1, -3]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aVzqYHWUEe2zo5QG_cHe4w" id="(0.4186046511627907,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bJZqgHWUEe2zo5QG_cHe4w" type="4001" element="_bJZDcHWUEe2zo5QG_cHe4w" source="_XV7_9HWUEe2zo5QG_cHe4w" target="_ayKrvXWTEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bJZqg3WUEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bJZqhHWUEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bJZqgXWUEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bJZqgnWUEe2zo5QG_cHe4w" points="[9, -7, -110, 87]$[119, -109, 0, -15]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bJa4oHWUEe2zo5QG_cHe4w" id="(0.16,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_e72ocHWUEe2zo5QG_cHe4w" type="4001" element="_e72BYHWUEe2zo5QG_cHe4w" source="_XV7_9HWUEe2zo5QG_cHe4w" target="_Tk3iHHWUEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_e72oc3WUEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_e72odHWUEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_e72ocXWUEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_e72ocnWUEe2zo5QG_cHe4w" points="[0, 5, -16, -195]$[14, 192, -2, -8]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fw0hk3WUEe2zo5QG_cHe4w" type="4001" element="_fw0hkHWUEe2zo5QG_cHe4w" source="_XV7_9HWUEe2zo5QG_cHe4w" target="_TFhwIHWTEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fw1IoHWUEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fw1IoXWUEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fw0hlHWUEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fw0hlXWUEe2zo5QG_cHe4w" points="[11, 11, -120, -610]$[119, 11, -12, -610]$[119, 275, -12, -346]$[124, 275, -7, -346]$[124, 591, -7, -30]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_i0BM0HWUEe2zo5QG_cHe4w" id="(0.38016528925619836,0.016666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qgvn8HWUEe2zo5QG_cHe4w" type="4001" element="_qgvA4HWUEe2zo5QG_cHe4w" source="_Tk3iHHWUEe2zo5QG_cHe4w" target="_npDCEHWUEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qgvn83WUEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qgvn9HWUEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qgvn8XWUEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qgvn8nWUEe2zo5QG_cHe4w" points="[28, -13, -124, 147]$[158, -13, 6, 147]$[158, -157, 6, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qgw2EHWUEe2zo5QG_cHe4w" id="(0.7910447761194029,0.373134328358209)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qgw2EXWUEe2zo5QG_cHe4w" id="(0.5116279069767442,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r9Tsk3WUEe2zo5QG_cHe4w" type="4001" element="_r9TskHWUEe2zo5QG_cHe4w" source="_TFhwIHWTEe2zo5QG_cHe4w" target="_npDCEHWUEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r9UToHWUEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r9UToXWUEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r9TslHWUEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r9TslXWUEe2zo5QG_cHe4w" points="[45, -1, -36, 0]$[79, -2, -2, -1]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_r9U6sHWUEe2zo5QG_cHe4w" id="(0.11627906976744186,0.46511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_u6JRInWUEe2zo5QG_cHe4w" type="4001" element="_u6IqEHWUEe2zo5QG_cHe4w" source="_ayKrvXWTEe2zo5QG_cHe4w" target="_npDCEHWUEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_u6JRJXWUEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_u6J4MHWUEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_u6JRI3WUEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_u6JRJHWUEe2zo5QG_cHe4w" points="[5, 6, 1, -179]$[5, 190, 1, 5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0qwk4HWUEe2zo5QG_cHe4w" type="4001" element="_0qv90HWUEe2zo5QG_cHe4w" source="_npDCEHWUEe2zo5QG_cHe4w" target="_w2QYgHWUEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0qwk43WUEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0qwk5HWUEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0qwk4XWUEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0qwk4nWUEe2zo5QG_cHe4w" points="[10, 2, -52, 2]$[60, 8, -2, 8]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5QmuonWUEe2zo5QG_cHe4w" type="4001" element="_5QmHkHWUEe2zo5QG_cHe4w" source="_w2QYgHWUEe2zo5QG_cHe4w" target="_C0KP4HWSEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5QmupXWUEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5QmupnWUEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5Qmuo3WUEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5QmupHWUEe2zo5QG_cHe4w" points="[-9, -12, 615, 923]$[-9, -993, 615, -58]$[-621, -993, 3, -58]$[-621, -954, 3, -19]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MV9O4HWVEe2zo5QG_cHe4w" type="4001" element="_MV3vUHWVEe2zo5QG_cHe4w" source="_w2QYgHWUEe2zo5QG_cHe4w" target="_HXslI3WVEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MV918HWVEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MV918XWVEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MV9O4XWVEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MV9O4nWVEe2zo5QG_cHe4w" points="[22, 0, -55, 169]$[75, 0, -2, 169]$[75, -144, -2, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_V2a4gHWVEe2zo5QG_cHe4w" type="4001" element="_V2VY8HWVEe2zo5QG_cHe4w" source="_C0KP4HWSEe2zo5QG_cHe4w" target="_vfo_WHWeEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_V2a4g3WVEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_V2a4hHWVEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_V2a4gXWVEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_V2a4gnWVEe2zo5QG_cHe4w" points="[2, 9, -10, -45]$[-13, 50, -25, -4]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WkPAw3WVEe2zo5QG_cHe4w" type="4001" element="_WkPAwHWVEe2zo5QG_cHe4w" source="_vfo_WHWeEe2zo5QG_cHe4w" target="_GplpUHWSEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WkPAxnWVEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WkPAx3WVEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WkPAxHWVEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WkPAxXWVEe2zo5QG_cHe4w" points="[-4, 12, 7, -32]$[-13, 37, -2, -7]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XpyTk3WVEe2zo5QG_cHe4w" type="4001" element="_XpyTkHWVEe2zo5QG_cHe4w" source="_HXslI3WVEe2zo5QG_cHe4w" target="_O9rfEHWVEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XpyTlnWVEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XpyTl3WVEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XpyTlHWVEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XpyTlXWVEe2zo5QG_cHe4w" points="[-2, -13, 1, 74]$[-2, -97, 1, -10]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YqzrsHWVEe2zo5QG_cHe4w" type="4001" element="_YqzEoHWVEe2zo5QG_cHe4w" source="_O9rfEHWVEe2zo5QG_cHe4w" target="_C0KP4HWSEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Yqzrs3WVEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YqzrtHWVEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YqzrsXWVEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YqzrsnWVEe2zo5QG_cHe4w" points="[-24, 15, 675, 593]$[-24, -660, 675, -82]$[-699, -660, 0, -82]$[-699, -599, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Yq050HWVEe2zo5QG_cHe4w" id="(0.5581395348837209,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lhN9cHWVEe2zo5QG_cHe4w" type="4001" element="_lhId4HWVEe2zo5QG_cHe4w" source="_O9rfEHWVEe2zo5QG_cHe4w" target="_zGfKOXWeEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lhN9c3WVEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lhN9dHWVEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lhN9cXWVEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lhN9cnWVEe2zo5QG_cHe4w" points="[4, -7, -27, 57]$[32, -60, 1, 4]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lhOkgHWVEe2zo5QG_cHe4w" id="(0.58,0.84)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_puQlo3WVEe2zo5QG_cHe4w" type="4001" element="_puQloHWVEe2zo5QG_cHe4w" source="_zGfKOXWeEe2zo5QG_cHe4w" target="_oEaS8HWVEe2zo5QG_cHe4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_puRMsHWVEe2zo5QG_cHe4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_puRMsXWVEe2zo5QG_cHe4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_puQlpHWVEe2zo5QG_cHe4w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_puQlpXWVEe2zo5QG_cHe4w" points="[0, -12, 0, 35]$[0, -47, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
